package calculo;

import java.awt.Image;
import javax.swing.ImageIcon;

public class form2 extends javax.swing.JFrame {
    
    public form2() {
        initComponents();
        scaleImage();
        HBajo.setVisible(false);
        HNormal.setVisible(false);
        HSobre.setVisible(false);
        HObes.setVisible(false);
        MBajo.setVisible(false);
        MNormal.setVisible(false);
        MSobre.setVisible(false);
        MObes.setVisible(false);
    }
    
    public void scaleImage(){
      
        
        ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/fondo3.jpg"));
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel6.getWidth() , jLabel6.getHeight() , Image.SCALE_SMOOTH);
        ImageIcon ScaledIcon = new ImageIcon(imgScale);
        jLabel6.setIcon(ScaledIcon);
        
        ImageIcon icon2 = new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/go.png"));
        Image img2 = icon2.getImage();
        Image imgScale2 = img2.getScaledInstance(Conf.getWidth() , Conf.getHeight() , Image.SCALE_SMOOTH);
        ImageIcon ScaledIcon2 = new ImageIcon(imgScale2);
        Conf.setIcon(ScaledIcon2);
        
        ImageIcon icon3 = new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/back.png"));
        Image img3 = icon3.getImage();
        Image imgScale3 = img3.getScaledInstance(back.getWidth() , back.getHeight() , Image.SCALE_SMOOTH);
        ImageIcon ScaledIcon3 = new ImageIcon(imgScale3);
        back.setIcon(ScaledIcon3);
       
        ImageIcon icon4 = new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/meh.png"));
        Image img4 = icon4.getImage();
        Image imgScale4 = img4.getScaledInstance(meh.getWidth() , meh.getHeight() , Image.SCALE_SMOOTH);
        ImageIcon ScaledIcon4 = new ImageIcon(imgScale4);
        meh.setIcon(ScaledIcon4);
        meh.setVisible(false);
        
        ImageIcon icon5 = new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/sad.png"));
        Image img5 = icon5.getImage();
        Image imgScale5 = img5.getScaledInstance(sad.getWidth() , sad.getHeight() , Image.SCALE_SMOOTH);
        ImageIcon ScaledIcon5 = new ImageIcon(imgScale5);
        sad.setIcon(ScaledIcon5);
        sad.setVisible(false);
        
        ImageIcon icon6 = new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/sceptic.png"));
        Image img6 = icon6.getImage();
        Image imgScale6 = img6.getScaledInstance(sceptic.getWidth() , sceptic.getHeight() , Image.SCALE_SMOOTH);
        ImageIcon ScaledIcon6 = new ImageIcon(imgScale6);
        sceptic.setIcon(ScaledIcon6);
        sceptic.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form1.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        PesoMujer = new javax.swing.ButtonGroup();
        PesoHombre = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        hBoton = new javax.swing.JRadioButton();
        mBoton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        Edad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        MBajo = new javax.swing.JToggleButton();
        MNormal = new javax.swing.JToggleButton();
        MSobre = new javax.swing.JToggleButton();
        MObes = new javax.swing.JToggleButton();
        HSobre = new javax.swing.JToggleButton();
        HBajo = new javax.swing.JToggleButton();
        HNormal = new javax.swing.JToggleButton();
        HObes = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        Check1 = new javax.swing.JCheckBox();
        Check2 = new javax.swing.JCheckBox();
        Check3 = new javax.swing.JCheckBox();
        Check4 = new javax.swing.JCheckBox();
        Check5 = new javax.swing.JCheckBox();
        Check6 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        JLabel20 = new javax.swing.JLabel();
        riesgo = new javax.swing.JTextField();
        categoria = new javax.swing.JTextField();
        Conf = new javax.swing.JButton();
        meh = new javax.swing.JLabel();
        sad = new javax.swing.JLabel();
        sceptic = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));
        jPanel1.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel13.setText("Selecciona los factores que presentas:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 50, 350, 30);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel1.setText("Sexo:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 103, 150, 19);

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 36)); // NOI18N
        jLabel11.setText("Mortalidad de la Influenza");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 10, 402, 47);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/back.png"))); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setFocusable(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(650, 20, 30, 20);

        Sexo.add(hBoton);
        hBoton.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        hBoton.setText("Hombre");
        hBoton.setContentAreaFilled(false);
        hBoton.setFocusable(false);
        hBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hBotonActionPerformed(evt);
            }
        });
        jPanel1.add(hBoton);
        hBoton.setBounds(10, 120, 90, 27);

        Sexo.add(mBoton);
        mBoton.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        mBoton.setText("Mujer");
        mBoton.setContentAreaFilled(false);
        mBoton.setFocusable(false);
        mBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBotonActionPerformed(evt);
            }
        });
        jPanel1.add(mBoton);
        mBoton.setBounds(110, 120, 80, 27);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel2.setText("Edad:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 161, 60, 19);

        Edad.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        Edad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selecciona...", "menor de 18", "18 a 30", "30 a 45", "45 a 65", "mayor de 65" }));
        Edad.setFocusable(false);
        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });
        jPanel1.add(Edad);
        Edad.setBounds(70, 160, 150, 25);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel3.setText("Peso Actual:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 196, 455, 19);

        PesoMujer.add(MBajo);
        MBajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/MBajo.png"))); // NOI18N
        MBajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBajoActionPerformed(evt);
            }
        });
        jPanel1.add(MBajo);
        MBajo.setBounds(27, 216, 56, 149);

        PesoMujer.add(MNormal);
        MNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/MNormal.png"))); // NOI18N
        jPanel1.add(MNormal);
        MNormal.setBounds(89, 216, 63, 149);

        PesoMujer.add(MSobre);
        MSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/MSobre.png"))); // NOI18N
        jPanel1.add(MSobre);
        MSobre.setBounds(158, 216, 63, 149);

        PesoMujer.add(MObes);
        MObes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/MObes.png"))); // NOI18N
        jPanel1.add(MObes);
        MObes.setBounds(227, 216, 56, 149);

        PesoHombre.add(HSobre);
        HSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/HSobre.png"))); // NOI18N
        HSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HSobreActionPerformed(evt);
            }
        });
        jPanel1.add(HSobre);
        HSobre.setBounds(158, 216, 60, 149);

        PesoHombre.add(HBajo);
        HBajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/HBajo.png"))); // NOI18N
        HBajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HBajoActionPerformed(evt);
            }
        });
        jPanel1.add(HBajo);
        HBajo.setBounds(27, 216, 60, 149);

        PesoHombre.add(HNormal);
        HNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/HNormal.png"))); // NOI18N
        HNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HNormalActionPerformed(evt);
            }
        });
        jPanel1.add(HNormal);
        HNormal.setBounds(89, 216, 60, 149);

        PesoHombre.add(HObes);
        HObes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/HObes.png"))); // NOI18N
        HObes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HObesActionPerformed(evt);
            }
        });
        jPanel1.add(HObes);
        HObes.setBounds(227, 216, 60, 149);

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel4.setText("Padecimientos:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 383, 96, 19);

        Check1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        Check1.setText("Hipertension");
        Check1.setContentAreaFilled(false);
        Check1.setFocusable(false);
        jPanel1.add(Check1);
        Check1.setBounds(10, 408, 210, 27);

        Check2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        Check2.setText("Diabetes");
        Check2.setContentAreaFilled(false);
        Check2.setFocusable(false);
        jPanel1.add(Check2);
        Check2.setBounds(10, 433, 200, 27);

        Check3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        Check3.setText("Consumo de Tabaco");
        Check3.setContentAreaFilled(false);
        Check3.setFocusable(false);
        jPanel1.add(Check3);
        Check3.setBounds(10, 459, 320, 27);

        Check4.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        Check4.setText("Enfermedad Pulmonar Obstructiva Cronica");
        Check4.setContentAreaFilled(false);
        Check4.setFocusable(false);
        jPanel1.add(Check4);
        Check4.setBounds(10, 487, 460, 27);

        Check5.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        Check5.setText("Inmunosupresion");
        Check5.setContentAreaFilled(false);
        Check5.setFocusable(false);
        jPanel1.add(Check5);
        Check5.setBounds(10, 513, 290, 27);

        Check6.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        Check6.setText("Enfermedad Cardiovascular");
        Check6.setContentAreaFilled(false);
        Check6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check6ActionPerformed(evt);
            }
        });
        jPanel1.add(Check6);
        Check6.setBounds(10, 539, 280, 27);

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel5.setText("Factores de riesgo:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 130, 220, 14);

        JLabel20.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        JLabel20.setText("Categoria de riesgo:");
        jPanel1.add(JLabel20);
        JLabel20.setBounds(350, 170, 230, 14);

        riesgo.setEditable(false);
        riesgo.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        riesgo.setText("0/9");
        riesgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riesgoActionPerformed(evt);
            }
        });
        jPanel1.add(riesgo);
        riesgo.setBounds(570, 120, 80, 30);

        categoria.setEditable(false);
        categoria.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaActionPerformed(evt);
            }
        });
        jPanel1.add(categoria);
        categoria.setBounds(570, 160, 200, 32);

        Conf.setBorderPainted(false);
        Conf.setContentAreaFilled(false);
        Conf.setFocusable(false);
        Conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfActionPerformed(evt);
            }
        });
        jPanel1.add(Conf);
        Conf.setBounds(480, 460, 100, 100);
        jPanel1.add(meh);
        meh.setBounds(430, 210, 210, 220);
        jPanel1.add(sad);
        sad.setBounds(430, 210, 210, 220);
        jPanel1.add(sceptic);
        sceptic.setBounds(430, 210, 210, 220);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 820, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Check6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Check6ActionPerformed

    private void HObesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HObesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HObesActionPerformed

    private void HNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HNormalActionPerformed

    private void HBajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HBajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HBajoActionPerformed

    private void HSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HSobreActionPerformed

    private void MBajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MBajoActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed

    }//GEN-LAST:event_EdadActionPerformed

    private void mBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBotonActionPerformed
        if(mBoton.isSelected()){
            MBajo.setVisible(true);
            MNormal.setVisible(true);
            MSobre.setVisible(true);
            MObes.setVisible(true);
            HBajo.setVisible(false);
            HNormal.setVisible(false);
            HSobre.setVisible(false);
            HObes.setVisible(false);
        }
    }//GEN-LAST:event_mBotonActionPerformed

    private void hBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hBotonActionPerformed
        if(hBoton.isSelected()){
            HBajo.setVisible(true);
            HNormal.setVisible(true);
            HSobre.setVisible(true);
            HObes.setVisible(true);
            MBajo.setVisible(false);
            MNormal.setVisible(false);
            MSobre.setVisible(false);
            MObes.setVisible(false);
        }
    }//GEN-LAST:event_hBotonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        menu regresar = new menu();
        setVisible(false);
        regresar.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void riesgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riesgoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riesgoActionPerformed

    private void categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaActionPerformed

    private void ConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfActionPerformed
        riesgo();
        riesgo.setText(Suma()+"/9");
    }//GEN-LAST:event_ConfActionPerformed
    
    private int Suma(){
        int factores = 0;
        int i = Edad.getSelectedIndex();
        
        if(hBoton.isSelected()){
            factores = factores +1;
        }
        if(i>=4){
            factores = factores + 1;
        }
        if(HSobre.isSelected()||HObes.isSelected()||MSobre.isSelected()||MObes.isSelected()){
            factores = factores + 1;
        }
        if(Check1.isSelected()){
            factores = factores + 1;
        }
        if(Check2.isSelected()){
            factores = factores + 1;
        }
        if(Check3.isSelected()){
            factores = factores + 1;
        }
        if(Check4.isSelected()){
            factores = factores + 1;
        }
        if(Check5.isSelected()){
            factores = factores + 1;
        }
        if(Check6.isSelected()){
            factores = factores + 1;
        }
        
        return factores;
    }
    
    private void riesgo(){
        int risk = Suma();
        
        if(risk<=3){
            categoria.setText("RIESGO MEDIO");
            meh.setVisible(true);
        }else{ 
            if(risk>3&&risk<=6){
                categoria.setText("RIESGO ALTO");
                sad.setVisible(true);
            }else{
                if(risk>6&&risk<=9){
                    categoria.setText("RIESGO MUY ALTO");
                    sceptic.setVisible(true);
                }
            }
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form1 */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Check1;
    private javax.swing.JCheckBox Check2;
    private javax.swing.JCheckBox Check3;
    private javax.swing.JCheckBox Check4;
    private javax.swing.JCheckBox Check5;
    private javax.swing.JCheckBox Check6;
    private javax.swing.JButton Conf;
    private javax.swing.JComboBox<String> Edad;
    private javax.swing.JToggleButton HBajo;
    private javax.swing.JToggleButton HNormal;
    private javax.swing.JToggleButton HObes;
    private javax.swing.JToggleButton HSobre;
    private javax.swing.JLabel JLabel20;
    private javax.swing.JToggleButton MBajo;
    private javax.swing.JToggleButton MNormal;
    private javax.swing.JToggleButton MObes;
    private javax.swing.JToggleButton MSobre;
    private javax.swing.ButtonGroup PesoHombre;
    private javax.swing.ButtonGroup PesoMujer;
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JButton back;
    private javax.swing.JTextField categoria;
    private javax.swing.JRadioButton hBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mBoton;
    private javax.swing.JLabel meh;
    private javax.swing.JTextField riesgo;
    private javax.swing.JLabel sad;
    private javax.swing.JLabel sceptic;
    // End of variables declaration//GEN-END:variables
}
