package calculo;

import java.awt.Image;
import javax.swing.ImageIcon;

public class menu extends javax.swing.JFrame {
    
    public menu() {
        initComponents();
        scaleImage();
    }
    
     public void scaleImage(){
      
        
        ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/fondo2.jpg"));
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel7.getWidth() , jLabel7.getHeight() , Image.SCALE_SMOOTH);
        ImageIcon ScaledIcon = new ImageIcon(imgScale);
        jLabel7.setIcon(ScaledIcon);
    
        ImageIcon icon2 = new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/info.png"));
        Image img2 = icon2.getImage();
        Image imgScale2 = img2.getScaledInstance(inInf.getWidth() , inInf.getHeight() , Image.SCALE_SMOOTH);
        ImageIcon ScaledIcon2 = new ImageIcon(imgScale2);
        inInf.setIcon(ScaledIcon2);
        
        ImageIcon icon3 = new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/info.png"));
        Image img3 = icon3.getImage();
        Image imgScale3 = img3.getScaledInstance(inCor.getWidth() , inCor.getHeight() , Image.SCALE_SMOOTH);
        ImageIcon ScaledIcon3 = new ImageIcon(imgScale3);
        inCor.setIcon(ScaledIcon3);
        
        ImageIcon icon4 = new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/info.png"));
        Image img4 = icon4.getImage();
        Image imgScale4 = img4.getScaledInstance(inEbola.getWidth() , inEbola.getHeight() , Image.SCALE_SMOOTH);
        ImageIcon ScaledIcon4 = new ImageIcon(imgScale4);
        inEbola.setIcon(ScaledIcon4);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ebola = new javax.swing.JButton();
        influenza = new javax.swing.JButton();
        corona = new javax.swing.JButton();
        inCor = new javax.swing.JButton();
        inInf = new javax.swing.JButton();
        inEbola = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(null);

        ebola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/ebola.png"))); // NOI18N
        ebola.setToolTipText("");
        ebola.setBorderPainted(false);
        ebola.setContentAreaFilled(false);
        ebola.setFocusable(false);
        ebola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebolaActionPerformed(evt);
            }
        });
        jPanel1.add(ebola);
        ebola.setBounds(440, 140, 195, 127);

        influenza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/influenza.png"))); // NOI18N
        influenza.setToolTipText("");
        influenza.setBorderPainted(false);
        influenza.setContentAreaFilled(false);
        influenza.setFocusable(false);
        influenza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                influenzaActionPerformed(evt);
            }
        });
        jPanel1.add(influenza);
        influenza.setBounds(230, 150, 195, 127);

        corona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/corona.png"))); // NOI18N
        corona.setToolTipText("");
        corona.setBorderPainted(false);
        corona.setContentAreaFilled(false);
        corona.setFocusable(false);
        corona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coronaActionPerformed(evt);
            }
        });
        jPanel1.add(corona);
        corona.setBounds(20, 150, 195, 127);

        inCor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/info.png"))); // NOI18N
        inCor.setBorderPainted(false);
        inCor.setContentAreaFilled(false);
        inCor.setFocusable(false);
        inCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inCorActionPerformed(evt);
            }
        });
        jPanel1.add(inCor);
        inCor.setBounds(180, 290, 25, 25);

        inInf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/info.png"))); // NOI18N
        inInf.setBorderPainted(false);
        inInf.setContentAreaFilled(false);
        inInf.setFocusable(false);
        inInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inInfActionPerformed(evt);
            }
        });
        jPanel1.add(inInf);
        inInf.setBounds(380, 290, 25, 25);

        inEbola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/resources/info.png"))); // NOI18N
        inEbola.setBorderPainted(false);
        inEbola.setContentAreaFilled(false);
        inEbola.setFocusable(false);
        inEbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inEbolaActionPerformed(evt);
            }
        });
        jPanel1.add(inEbola);
        inEbola.setBounds(570, 290, 25, 25);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jLabel1.setText("Mortalidad de un Virus");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 20, 330, 30);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel2.setText("Coronavirus");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 290, 130, 20);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel3.setText("Influenza");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 290, 100, 20);

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel4.setText("Ébola");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(500, 290, 70, 20);

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        jLabel5.setText("Elige un virus para saber el riesgo de mortalidad");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 100, 500, 21);

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel6.setText("o selecciona el icono para mas informacion acerca de cada virus");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 390, 550, 20);

        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 660, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ebolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebolaActionPerformed
        form3 ebo = new form3();
        setVisible(false);
        ebo.setVisible(true);
    }//GEN-LAST:event_ebolaActionPerformed

    private void influenzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_influenzaActionPerformed
        form2 inf = new form2();
        setVisible(false);
        inf.setVisible(true);
    }//GEN-LAST:event_influenzaActionPerformed

    private void coronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coronaActionPerformed
        form1 cor = new form1();
        setVisible(false);
        cor.setVisible(true);
    }//GEN-LAST:event_coronaActionPerformed

    private void inCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inCorActionPerformed
        info1 cor = new info1();
        setVisible(false);
        cor.setVisible(true);
    }//GEN-LAST:event_inCorActionPerformed

    private void inInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inInfActionPerformed
        Influ cor2 = new Influ();
        setVisible(false);
        cor2.setVisible(true);
    }//GEN-LAST:event_inInfActionPerformed

    private void inEbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inEbolaActionPerformed
        info3 cor3 = new info3();
        setVisible(false);
        cor3.setVisible(true);
    }//GEN-LAST:event_inEbolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton corona;
    private javax.swing.JButton ebola;
    private javax.swing.JButton inCor;
    private javax.swing.JButton inEbola;
    private javax.swing.JButton inInf;
    private javax.swing.JButton influenza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
